# MODEL RUNNER
models:
  llm:
    model: ai/qwen3:8B-Q4_K_M
    # context_size: 8192
  

services:
  # STATIC
  # static_html:
  #   build:
  #     context: ./static_html
  #     dockerfile: static.Dockerfile
  #   ports:
  #     - "8000:8000"
  #   command: ["python", "-m", "http.server", "8000"]
  #   volumes:
  #     - ./static_html/src:/app/src

  # BACKEND
  app:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8080:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend/src:/app
    environment:
      - PORT=8000
      - MY_PROJECT=hello world
    env_file:
      - .env
    depends_on:
      db_service:
        condition: service_healthy
    models:
      llm:
        endpoint_var: LLM_ENDPOINT
        model_var: LLM_MODEL_NAME
    develop:
      watch:
      - action: rebuild
        path: backend/requirements.txt
      - action: rebuild
        path: backend/Dockerfile
      # - action: restart
      #   path: backend/src
      # - action: sync+restart
      #   path: backend/src
      #   target: /app

  # DATABASE
  db_service:
    image: postgres:17.5-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - dc_managed_db_volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5


volumes:
  dc_managed_db_volume:
